name: PowerBI Performance Data Collection

on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PowerShell Modules
      run: |
        Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
      shell: pwsh

    - name: Run PowerBI Performance Script
      run: |
        $username = "ServiceAccount@technologycue.com"
        $password = "ILuvBIT!"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $securePassword
        Connect-PowerBIServiceAccount -Credential $cred

        $allWorkspaces = Get-PowerBIWorkspace -Scope Organization -ALL
        
        $results = foreach ($workspace in $allWorkspaces) {
          [PSCustomObject]@{
              "Id"                    = $workspace.Id
              "Name"                  = $workspace.Name
              "Type"                  = $workspace.Type
              "State"                 = $workspace.State
              "IsReadOnly"            = $workspace.IsReadOnly
              "IsOrphaned"            = $workspace.IsOrphaned
              "IsOnDedicatedCapacity" = $workspace.IsOnDedicatedCapacity
              "CapacityId"            = $workspace.CapacityId
              "UsersCount"            = ($workspace.Users.Count | Measure-Object -Sum).Sum
              "UserNames"             = ($workspace.Users.UserPrincipalName -replace '@.*\.com') -join ', '
          }
        }
            
        $outputPath = "C:\\Users\\user\\Desktop\\PowerBI\\Workout"
        $results | Export-Csv -Path "$outputPath\\workspaceSummary.csv" -NoTypeInformation
